# .github/ISSUE_TEMPLATE/sprint-task.yml
---
name: 🏷 Sprint Task
description: A ticket for our 2-week Sprint
title: "[SPRINT] "
labels: ["Backlog","type:Task"]
assignees: ["@Khumo1"]
projects:
  - https://github.com/users/Khumo1/projects/1
---

## Description
…
